/*
 * Auto-generated ESP32 code
 * Generated by Atech Hardware Platform
 * Using athera module drivers with FreeRTOS tasks
 */

// ========== INCLUDES ==========
#include <Arduino.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_task_wdt.h"
#include "esp_system.h"
#include <Preferences.h>
#include "modules/shared/atech_helpers.h"
#include "modules/shared/atech_ui.h"
#include "modules/connectivity/wifi_ws_templates.h"
#include <Wire.h>
#include <i2c_interface.h>
#include <i2c_hardware.h>
#include <i2c_software.h>
#include "modules/display/st7735_tft.h"
#include "modules/sensor/icm40608.h"
#include "modules/distance/vl53l5cx.h"
// EMBEDDED_SOUNDS_FP: none

// ========== FREERTOS TASK HANDLES ==========
TaskHandle_t displaytaskHandle = NULL;
TaskHandle_t streamtaskHandle = NULL;

// ========== GLOBAL VARIABLES ==========
// ========== WIFI TRANSPORT ==========
WiFiNetwork wifi_networks[] = {
  {"GNX161DE2", "ADWVK42Z9XPA", 10},
};

AtechWiFi wifi(wifi_networks, 1, "gateway.atech.dev", 443, "012a8d5c-dbb2-4055-8419-9113b3c9fe18", true);

// ========== I2C INTERFACES ==========
// Hardware I2C buses (clock set per-bus in setup; see begin())
WireI2C i2c_port_7(Wire1, 6, 7);
WireI2C i2c_port_14(Wire, 36, 35);

// ========== MODULE INSTANCES ==========
// ST7735 TFT Color Display (160x80)
// Pins swapped for left-side placement: port_2 pins first, port_1 pins second
ST7735_TFT st7735_tft_1(8, 4, 9, 5);
// 6-Axis IMU (ICM-40608 or LSM6DSOX)
ICM40608 icm40608_1(&i2c_port_7);
// VL53L5CX 8x8 Distance Sensor
VL53L5CX_Sensor vl53l5cx_1(Wire);


// User behavior variables and helper functions
#include <Fonts/FreeSans9pt7b.h>
#include <Fonts/FreeSansBold18pt7b.h>
#define UI_BG     ST7735_TFT::COLOR_BLACK
#define UI_LABEL  ST7735_TFT::COLOR_WHITE
#define UI_VALUE  ST7735_TFT::COLOR_CYAN
#define UI_ALERT  ST7735_TFT::COLOR_ORANGE
unsigned long lastDisplayMs = 0;
unsigned long lastStreamMs = 0;
unsigned long lastWifiCheckMs = 0;
float lastMetersShown = -999.0f;
bool lastWasOOR = false;
void handleMessage(const char* action, const char* value) {
  // No project-level scene actions needed beyond the standard display primitives;
  // this project is primarily a live sensor stream + readout, so we just guard against
  // unexpected payloads and ignore anything not recognized.
  if (action == nullptr) return;
  (void)value;
}

// ========== FREERTOS TASKS ==========
// DisplayTask Task (runs every 100ms)
void displaytaskTask(void* parameter) {
  esp_task_wdt_add(NULL);  // Subscribe to task watchdog (30s timeout)
  uint32_t _lastHeapLog = 0;  // Periodic heap canary (this task carries it)
  while (true) {
    esp_task_wdt_reset();
    uint32_t _nowMs = millis();
    if (_nowMs - _lastHeapLog > 30000) {
      _lastHeapLog = _nowMs;
      Serial.printf("[Atech heap] free=%u min=%u\n", (unsigned)ESP.getFreeHeap(), (unsigned)ESP.getMinFreeHeap());
    }
    int16_t minDistMm = vl53l5cx_1.getMinDistance();
    bool oor = (minDistMm >= 32767);
    float meters = oor ? 0.0f : (minDistMm / 1000.0f);
    bool changed = oor != lastWasOOR || fabsf(meters - lastMetersShown) >= 0.01f;
    if (changed) {
    lastMetersShown = meters;
    lastWasOOR = oor;
    st7735_tft_1.fillRect(6, 24, 148, 50, UI_BG);
    st7735_tft_1.setFont(&FreeSansBold18pt7b);
    if (oor) {
    st7735_tft_1.setTextColor(UI_ALERT);
    st7735_tft_1.setCursor(8, 62);
    st7735_tft_1.print("--.--");
    } else {
    st7735_tft_1.setTextColor(UI_VALUE);
    st7735_tft_1.setCursor(8, 62);
    st7735_tft_1.print(meters, 2);
    }
    st7735_tft_1.setFont(&FreeSans9pt7b);
    st7735_tft_1.setTextColor(UI_LABEL);
    st7735_tft_1.setCursor(108, 62);
    st7735_tft_1.print("m");
    st7735_tft_1.display();
    }
    vTaskDelay(pdMS_TO_TICKS(100));
  }
}

// StreamTask Task (runs every 200ms)
void streamtaskTask(void* parameter) {
  esp_task_wdt_add(NULL);  // Subscribe to task watchdog (30s timeout)
  static bool _wasConnected = false;
  while (true) {
    esp_task_wdt_reset();
    wifi.maintain();
    bool _nowConnected = wifi.isConnected();
    if (_nowConnected != _wasConnected) {
      _wasConnected = _nowConnected;
      Serial.println(_nowConnected ? "[Atech] WiFi status: CONNECTED" : "[Atech] WiFi status: DISCONNECTED, retrying...");
    }
    unsigned long _nowMillis = millis();
    if (!_nowConnected && (_nowMillis - lastWifiCheckMs >= 2000)) {
      lastWifiCheckMs = _nowMillis;
      Serial.println("[Atech] WiFi reconnect attempt...");
      bool _reconnected = wifi.connect();
      Serial.println(_reconnected ? "[Atech] WiFi reconnect succeeded" : "[Atech] WiFi reconnect failed, will retry");
    }
    if (_nowConnected) {
    float ax = icm40608_1.readAccelX();
    float ay = icm40608_1.readAccelY();
    float az = icm40608_1.readAccelZ();
    float gx = icm40608_1.readGyroX();
    float gy = icm40608_1.readGyroY();
    float gz = icm40608_1.readGyroZ();
    float pitch = icm40608_1.getPitch();
    float roll = icm40608_1.getRoll();
    float tilt = icm40608_1.getTiltAngle();
    const char* ori = icm40608_1.getOrientationName();
    int16_t vl53l5cx_1_minDistMm = vl53l5cx_1.getMinDistance();

    bool _ok = true;
    _ok &= wifi.postSensorEvent("accel_x", ax, "icm40608_imu");
    _ok &= wifi.postSensorEvent("accel_y", ay, "icm40608_imu");
    _ok &= wifi.postSensorEvent("accel_z", az, "icm40608_imu");
    _ok &= wifi.postSensorEvent("gyro_x", gx, "icm40608_imu");
    _ok &= wifi.postSensorEvent("gyro_y", gy, "icm40608_imu");
    _ok &= wifi.postSensorEvent("gyro_z", gz, "icm40608_imu");

    char orientStr[96];
    snprintf(orientStr, sizeof(orientStr), "%.2f,%.2f,%.2f,%s", pitch, roll, tilt, ori);
    _ok &= wifi.postSensorEventStr("orientation", orientStr, "icm40608_imu");

    if (vl53l5cx_1_minDistMm < 32767) {
    _ok &= wifi.postSensorEventInt("distance", vl53l5cx_1_minDistMm, "vl53l5cx_distance");
    } else {
    _ok &= wifi.postSensorEventInt("distance", -1, "vl53l5cx_distance");
    }
    _ok &= wifi.postSensorEventInt("min_distance", (vl53l5cx_1_minDistMm < 32767) ? vl53l5cx_1_minDistMm : -1, "vl53l5cx_distance");
    if (!_ok) {
      Serial.println("[Atech] WiFi post failed, forcing reconnect check");
      lastWifiCheckMs = 0;
    }
    }
    vTaskDelay(pdMS_TO_TICKS(200));
  }
}

// ========== SETUP ==========
void setup() {
  Serial.setRxBufferSize(8192);
  Serial.begin(115200);
  Serial.setTxTimeoutMs(0);
  Serial.println("Initializing...");

  // ========== BOOT DIAGNOSTICS ==========
  {
    Preferences _bootPrefs;
    _bootPrefs.begin("atech_boot", false);
    uint32_t _bootCount = _bootPrefs.getUInt("count", 0) + 1;
    _bootPrefs.putUInt("count", _bootCount);
    _bootPrefs.end();

    esp_reset_reason_t _reason = esp_reset_reason();
    const char* _reasonStr = "UNKNOWN";
    switch (_reason) {
      case ESP_RST_POWERON:   _reasonStr = "POWERON";   break;
      case ESP_RST_EXT:       _reasonStr = "EXT_PIN";   break;
      case ESP_RST_SW:        _reasonStr = "SOFTWARE";  break;
      case ESP_RST_PANIC:     _reasonStr = "PANIC";     break;
      case ESP_RST_INT_WDT:   _reasonStr = "INT_WDT";   break;
      case ESP_RST_TASK_WDT:  _reasonStr = "TASK_WDT";  break;
      case ESP_RST_WDT:       _reasonStr = "OTHER_WDT"; break;
      case ESP_RST_DEEPSLEEP: _reasonStr = "DEEPSLEEP"; break;
      case ESP_RST_BROWNOUT:  _reasonStr = "BROWNOUT";  break;
      case ESP_RST_SDIO:      _reasonStr = "SDIO";      break;
      default: break;
    }

    Serial.println();
    Serial.println("================ ATECH BOOT ================");
    Serial.printf("  Boot count : %u\n", _bootCount);
    Serial.printf("  Reset cause: %s (%d)\n", _reasonStr, (int)_reason);
    Serial.printf("  Free heap  : %u bytes\n", (unsigned)ESP.getFreeHeap());
    Serial.printf("  Min heap   : %u bytes (lowest since boot)\n", (unsigned)ESP.getMinFreeHeap());
    Serial.printf("  CPU freq   : %u MHz\n", (unsigned)ESP.getCpuFreqMHz());
    Serial.println("============================================");
  }

  // Initialize I2C interfaces
  i2c_port_7.begin(400000);  // Hardware I2C at 400kHz
  i2c_port_14.begin(400000);  // Hardware I2C at 400kHz

  // Initialize modules
  st7735_tft_1.begin();
  st7735_tft_1.setRotation(1);  // Left side: rotated 180°
  delay(150);  // Allow display to stabilize
  if (!icm40608_1.begin()) {
    Serial.println("Failed to initialize 6-Axis IMU (ICM-40608 or LSM6DSOX)");
  }
  if (!vl53l5cx_1.begin()) {
    Serial.println("Failed to initialize VL53L5CX 8x8 Distance Sensor");
  }

  // ========== WIFI TRANSPORT ==========
  Serial.println("[Atech] Connecting to WiFi...");
  wifi.connect();
  if (wifi.isConnected()) {
    Serial.println("[Atech] WiFi connected");
  } else {
    Serial.println("[Atech] WiFi not yet connected, will retry in background");
  }
  Serial.println("[Atech] Transport: WiFi WebSocket");

  Serial.println("Setup complete!");

  // ========== USER BEHAVIOR SETUP ==========
  st7735_tft_1.fillScreen(UI_BG);
  st7735_tft_1.setFont(&FreeSans9pt7b);
  st7735_tft_1.setTextColor(UI_LABEL);
  st7735_tft_1.setCursor(8, 18);
  st7735_tft_1.print("Distance");
  st7735_tft_1.display();
  wifi.onMessage(handleMessage);

  // ========== TASK WATCHDOG ==========
  esp_task_wdt_init(30, true);  // 30s timeout, panic on trigger

  // ========== CREATE FREERTOS TASKS ==========
  // Creating 2 independent tasks on Core 1
  // DisplayTask: runs every 100ms, priority 2
  xTaskCreatePinnedToCore(
    displaytaskTask, "DisplayTask", 4096, NULL,
    2, &displaytaskHandle, 1
  );

  // StreamTask: runs every 200ms, priority 1
  xTaskCreatePinnedToCore(
    streamtaskTask, "StreamTask", 16384, NULL,
    1, &streamtaskHandle, 1
  );

  Serial.println("FreeRTOS tasks started!");
}

// ========== MAIN LOOP (empty - tasks handle everything) ==========
void loop() {
  // Nothing here - FreeRTOS tasks handle all operations
  // This allows other tasks and system processes to run
  vTaskDelay(portMAX_DELAY);
}